### ISSUE TITLE
Problem with project build

### ISSUE THREAD

**Issue by Green7** [OutSystems/ReactView#184]
Could you please provide more detailed instructions on how to build the project (under Windows)?

I'm trying to do this but without success.

- I built WebView and added the path containing the WebViewControl packages to nuget.config (in the ReactView directory)
- I built ViewGenerator.sln as well
- but I have problem with ReactView.sln. Even though nuget can list the WebViewControl-Avalonia.3.120.0 and WebViewControl-WPF.3.120.0 packages, the error "Unable to find package WebViewControl-Avalonia with version (>=) 3.120.0)" appears during compilation.

**Comment by joaompneves** [comment]
Hi. The WebViewControl-Avalonia version 3.120.0 wasn't for some reason was not published on nuget.org. Its is now. Please try again

**Comment by Green7** [comment]
Now it compiles without any problem. Thanks !
